### ISSUE TITLE
Question about data synthesis

### ISSUE THREAD

**Issue by Steve-Tod** [HobbitLong/shape2prog#2]
https://github.com/HobbitLong/shape2prog/blob/44ebb0c46148a7d3da77dcdfb28efe01d1884731/programs/program_table_1.py#L14

Hi, I'm trying to use your synthesized data, and I'm confused what does param `d` means here? I didn't find its appearance in function body.

**Comment by HobbitLong** [comment]
Hi,

You can find it here:
```
d = get_distance_to_center()
```
It simply means, for instance, in a 32 x 32 grids, what is the distance from each grid to the center. So it's also a 32 x 32 matrix.

**Comment by Steve-Tod** [comment]
Thanks, I see. But actually, it seems you didn't use this d in the function `generate_single`.😂

**Comment by HobbitLong** [comment]
Hi, @Steve-Tod,

Good catch!

Some function uses it, some does not. When copying the basic template, I did not explicitly remove `d` for every program template that does not use it.

**Comment by Steve-Tod** [comment]
I see😂 Thank you for answering!
